- name: Run Proxy
  community.docker.docker_container:
    name: httpd
    image: ilianbraka/tp-devops-httpd:latest
    pull: always
    ports:
      - "8088:8088"
    networks:
      - name: my-network
    state: started

