- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest
    update_cache: yes  # Assure que le cache est mis à jour avant d'installer les paquets

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
    state: present
    update_cache: yes  # Met à jour le cache des paquets après l'ajout du dépôt Docker

- name: Install Docker
  apt:
    name: docker-ce
    state: present  # Installe Docker Community Edition

- name: Ensure Docker is running
  service:
    name: docker
    state: started  # Démarre le service Docker

- name: Run HTTPD container
  docker_container:
    name: httpd
    image: httpd:latest  # Utilise l'image officielle HTTPD de Docker
    state: started  # Assure que le conteneur est en cours d'exécution
    restart_policy: always  # Assure que le conteneur redémarre automatiquement en cas de panne
