- name: Run Backend Application
  community.docker.docker_container:
    name: my-api
    image: ilianbraka/tp-devops-simple-api:latest
    pull: always
    ports:
      - "8080:8080"
    env:
      DATABASE_HOST: my-db
      DATABASE_PORT: "5432"
    networks:
      - name: my-network
    state: started
