all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /home/ilianbraka/.ssh/id_rsa
  children:
    prod:
      hosts:
        ilian.braka.takima.cloud:
          ansible_python_interpreter: /usr/bin/python3
