name: CI devops 2024

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04

    steps:
      # Étape 1 : Récupérer le code source depuis le dépôt GitHub
      - name: Checkout repository
        uses: actions/checkout@v2.5.0

      # Étape 2 : Configurer JDK 17 pour le projet
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Étape 3 : Construire et tester l'application avec Maven
      - name: Build and test with Maven
        run: mvn clean verify